###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: neusta-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=test123
        - MYSQL_DATABASE=neusta
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test123
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: neusta-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: neusta-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: neusta-phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
        - "8080:80"
      volumes:
        - /sessions
